setwd("C:\\Users\\aksha\\OneDrive\\Documents\\GitHub\\who-is-more-influential\\Data Analysis")
data=read.csv("train.csv")
head(data)
names(data)
newData=data.frame(data$Choice
                   ,log(1+data$A_follower_count)-log(1+data$B_follower_count)
                   ,log(1+data$A_following_count)-log(1+data$B_following_count)
                   ,log(1+data$A_listed_count)-log(1+data$B_listed_count)
                   ,log(1+data$A_mentions_received)-log(1+data$B_mentions_received)
                   ,log(1+data$A_retweets_received)-log(1+data$B_retweets_received)
                   ,log(1+data$A_mentions_sent)-log(1+data$B_mentions_sent)
                   ,log(1+data$A_retweets_sent)-log(1+data$B_retweets_sent)
                   ,log(1+data$A_posts)-log(1+data$B_posts)
                   ,log(1+data$A_network_feature_1)-log(1+data$B_network_feature_1)
                   ,log(1+data$A_network_feature_2)-log(1+data$B_network_feature_2)
                   ,log(1+data$A_network_feature_3)-log(1+data$B_network_feature_3))
head(newData)
write.csv(newData, "log_train_new.csv")

data=read.csv("test.csv")
head(data)
names(data)
newData=data.frame(log(1+data$A_follower_count)-log(1+data$B_follower_count)
                   ,log(1+data$A_following_count)-log(1+data$B_following_count)
                   ,log(1+data$A_listed_count)-log(1+data$B_listed_count)
                   ,log(1+data$A_mentions_received)-log(1+data$B_mentions_received)
                   ,log(1+data$A_retweets_received)-log(1+data$B_retweets_received)
                   ,log(1+data$A_mentions_sent)-log(1+data$B_mentions_sent)
                   ,log(1+data$A_retweets_sent)-log(1+data$B_retweets_sent)
                   ,log(1+data$A_posts)-log(1+data$B_posts)
                   ,log(1+data$A_network_feature_1)-log(1+data$B_network_feature_1)
                   ,log(1+data$A_network_feature_2)-log(1+data$B_network_feature_2)
                   ,log(1+data$A_network_feature_3)-log(1+data$B_network_feature_3))
head(newData)
write.csv(newData, "log_test_new.csv")
