library(ggplot2)
library(reshape2)
setwd("C:\\Users\\aksha\\OneDrive\\Documents\\GitHub\\who-is-more-influential\\Data Analysis")
data=read.csv("train.csv")
head(data)
names(data)
newData=data.frame(data$Choice
                  ,data$A_follower_count-data$B_follower_count
                  ,data$A_following_count-data$B_following_count
                  ,data$A_listed_count-data$B_listed_count
                  ,data$A_mentions_received-data$B_mentions_received
                  ,data$A_retweets_received-data$B_retweets_received
                  ,data$A_mentions_sent-data$B_mentions_sent
                  ,data$A_retweets_sent-data$B_retweets_sent
                  ,data$A_posts-data$B_posts
                  ,data$A_network_feature_1-data$B_network_feature_1
                  ,data$A_network_feature_2-data$B_network_feature_2
                  ,data$A_network_feature_3-data$B_network_feature_3)
head(newData)
ch=as.factor(newData$data.Choice)
summary(ch)
#################1
data_followers=ifelse(newData$data.A_follower_count...data.B_follower_count>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F1=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F1, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

#################2
data_followers=ifelse(newData$data.A_following_count...data.B_following_count>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F2=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F2, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

#################3
data_followers=ifelse(newData$data.A_listed_count...data.B_listed_count>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F3=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F3, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

#################4
data_followers=ifelse(newData$data.A_retweets_received...data.B_retweets_received>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F4=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F4, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

#################5
data_followers=ifelse(newData$data.A_mentions_sent...data.B_mentions_sent>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F5=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F5, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)


#################6
data_followers=ifelse(newData$data.A_mentions_received...data.B_mentions_received>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F6=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F6, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

#################7
data_followers=ifelse(newData$data.A_retweets_sent...data.B_retweets_sent>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F7=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F7, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

#################8
data_followers=ifelse(newData$data.A_posts...data.B_posts>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F8=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F8, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

#################9
data_followers=ifelse(newData$data.A_network_feature_1...data.B_network_feature_1>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F9=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F9, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

#################10
data_followers=ifelse(newData$data.A_network_feature_2...data.B_network_feature_2>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F10=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F10, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

#################11
data_followers=ifelse(newData$data.A_network_feature_3...data.B_network_feature_3>=0,1,0)
df=as.factor(data_followers)
summary(df)
counts <- data.frame(ch,df)
#summary(counts)
#str(counts)
freq=table(col(counts), as.matrix(counts))
#summary(freq)
#Plot the Data
Names=c("Actual","Predicted") 
Labels=c("B","A")
data=data.frame(cbind(freq),Names) 
data.m <- melt(data, id.vars='Names')
data.m$var=ifelse(data.m$variable=='X0','B is influential','A is influential')
data.m$F11=ifelse(data.m$variable=='X0','B','A')
ggplot(data.m, aes(F11, value)) + geom_bar(aes(fill = Names), position = "dodge", stat="identity")
#summary(data.m)
#str(data.m)

