setwd("C:\\Users\\aksha\\OneDrive\\Documents\\GitHub\\who-is-more-influential\\Data Analysis")
data=read.csv("train.csv")
head(data)
names(data)

newData=data.frame(data$Choice
                   ,(data$A_follower_count-mean(data$A_follower_count))/sd(data$A_follower_count)-(data$B_follower_count-mean(data$B_follower_count))/sd(data$B_follower_count)
                   ,(data$A_following_count-mean(data$A_following_count))/sd(data$A_following_count)-(data$B_following_count-mean(data$B_following_count))/sd(data$B_following_count)
                   ,(data$A_listed_count-mean(data$A_listed_count))/sd(data$A_listed_count)-(data$B_listed_count-mean(data$B_listed_count))/sd(data$B_listed_count)
                   ,(data$A_mentions_received-mean(data$A_mentions_received))/sd(data$A_mentions_received)-(data$B_mentions_received-mean(data$B_mentions_received))/sd(data$B_mentions_received)
                   ,(data$A_retweets_received-mean(data$A_retweets_received))/sd(data$A_retweets_received)-(data$B_retweets_received-mean(data$B_retweets_received))/sd(data$B_retweets_received)
                   ,(data$A_mentions_sent-mean(data$A_mentions_sent))/sd(data$A_mentions_sent)-(data$B_mentions_sent-mean(data$B_mentions_sent))/sd(data$B_mentions_sent)
                   ,(data$A_retweets_sent-mean(data$A_retweets_sent))/sd(data$A_retweets_sent)-(data$B_retweets_sent-mean(data$B_retweets_sent))/sd(data$B_retweets_sent)
                   ,(data$A_posts-mean(data$A_posts))/sd(data$A_posts)-(data$B_posts-mean(data$B_posts))/sd(data$B_posts)
                   ,(data$A_network_feature_1-mean(data$A_network_feature_1))/sd(data$A_network_feature_1)-(data$B_network_feature_1-mean(data$B_network_feature_1))/sd(data$B_network_feature_1)
                   ,(data$A_network_feature_2-mean(data$A_network_feature_2))/sd(data$A_network_feature_2)-(data$B_network_feature_2-mean(data$B_network_feature_2))/sd(data$B_network_feature_2)
                   ,(data$A_network_feature_3-mean(data$A_network_feature_3))/sd(data$A_network_feature_3)-(data$B_network_feature_3-mean(data$B_network_feature_3))/sd(data$B_network_feature_3))
head(newData)
write.csv(newData, "Normalized_train_new.csv")

data=read.csv("test.csv")
head(data)
names(data)
newData=data.frame(log(1+data$A_follower_count)-log(1+data$B_follower_count)
                   ,log(1+data$A_following_count)-log(1+data$B_following_count)
                   ,log(1+data$A_listed_count)-log(1+data$B_listed_count)
                   ,log(1+data$A_mentions_received)-log(1+data$B_mentions_received)
                   ,log(1+data$A_retweets_received)-log(1+data$B_retweets_received)
                   ,log(1+data$A_mentions_sent)-log(1+data$B_mentions_sent)
                   ,log(1+data$A_retweets_sent)-log(1+data$B_retweets_sent)
                   ,log(1+data$A_posts)-log(1+data$B_posts)
                   ,log(1+data$A_network_feature_1)-log(1+data$B_network_feature_1)
                   ,log(1+data$A_network_feature_2)-log(1+data$B_network_feature_2)
                   ,log(1+data$A_network_feature_3)-log(1+data$B_network_feature_3))
head(newData)
write.csv(newData, "log_test_new.csv")
